schoolProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from e_homework.views.auth_views import *
from e_homework.views.student_views import *
from e_homework.views.student_views import tag_info as tag_info_student
from e_homework.views.teacher_views import *
from e_homework.views.teacher_views import tag_info as tag_info_teacher

urlpatterns_auth = [
    url(r'^sign-in/do-sign-in/', do_sign_in, name='do-sign-in'),
    url(r'^sign-in/', sign_in),
    url(r'^sign-up/do-sign-up/', do_sign_up, name='do-sign-up'),
    url(r'^sign-up/', sign_up, name='sign-up'),
    url(r'^logout/', do_logout, name='log-out'),
    url(r'get-school-list/', get_school_list, name='get-school-list'),
    url(r'get-class-list/', get_class_list, name='get-class-list'),
    url(r'validate-username/', validate_username, name='validate-username'),
    url(r'validate-password/', validate_password, name='validate-password'),
    url(r'validate-user/', validate_user, name='validate-user'),
    url(r'validate-password-for-user/', validate_password_for_user, name='validate-password-for-user')
]
urlpatterns_teacher = [
    url(r'^new-vote/', new_vote, name='new-vote'),
    url(r'^do-create-new-vote/', do_create_new_vote, name='do-create-new-vote'),
    url(r'^list/vote/(\d+)/', vote_info, name='teacher-vote-list'),
    url(r'^list/', vote_list, name='teacher-vote-list'),
    url(r'^tag-info/', tag_info_teacher, name='tag-info-teacher'),
    url(r'^delete-vote/', delete_vote, name='delete-vote'),
    url(r'^modify-vote/(\d+)/student-info/', vote_student_info, name='vote-student-info'),
    url(r'^modify-vote/(\d+)/', modify_vote, name='modify-vote'),
    url(r'^$', teacher, name='teacher')
]
urlpatterns_student = [
    url(r'^vote/(\d+)/', vote, name='vote'),
    url(r'^do-vote/(\d+)/', do_vote, name='do-vote'),
    url(r'^tag-info/', tag_info_student, name='tag-info-student'),
    url(r'^$', student, name='student')
]
urlpatterns = urlpatterns_auth + [
    url(r'^admin/', admin.site.urls),
    url(r'^teacher/', include(urlpatterns_teacher)),
    url(r'^student/', include(urlpatterns_student)),
    url(r'^$', lambda _: redirect("/sign-in/"), name='sign-in')
]

e_homework/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.utils.timezone import now

from .mutiprocessing_map import map


def number_to_chinese(number):
    """
    将数字转换为中文字符串
    """
    assert 0 < number < 100
    ret = ''
    number_to_chinese_map = {1: '一', 2: '二', 3: '三', 4: '四', 5: '五', 6: '六', 7: '七', 8: '八', 9: '九'}
    if 10 <= number <= 20:
        ret += '十'
    elif number > 20:
        ret += number_to_chinese_map[number // 10] + '十'
    if number % 10 != 0:
        ret += number_to_chinese_map[number % 10]
    return ret


class School(models.Model):
    """
    保存学校的类型和对应的用户
    """
    SCHOOL_TYPE_CHOICES = (
        ('小', '小学'),
        ('初', '初中'),
        ('高', '高中')
    )
    type = models.CharField(max_length=8, choices=SCHOOL_TYPE_CHOICES)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Class(models.Model):
    """
    保存某个班级是几年级、几班、属于哪个学校
    """
    grade_number = models.PositiveSmallIntegerField()
    class_number = models.PositiveIntegerField()
    school_belong_to = models.ForeignKey(School)

    def str_without_school_name(self):
        """
        :return: 不包含学校名称的班级名称，eg.高一(2)班
        """
        if self.grade_number == 0:
            assert self.school_belong_to.type == '初'
            return '预初' + '(' + str(self.class_number) + ')班'
        return self.school_belong_to.type + number_to_chinese(
            self.grade_number) + '(' + str(self.class_number) + ')班'

    def __str__(self):
        return str(self.school_belong_to) + ' ' + self.str_without_school_name()


class Teacher(models.Model):
    """
    保存教师的身份信息
    """
    school_belong_to = models.ForeignKey(School)
    classes_teaching = models.ManyToManyField(Class)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        permissions = (("teachers_permission", "teachers_permission"),)


class Student(models.Model):
    """
    保存学生的身份信息
    """
    user = models.OneToOneField(User)
    class_belong_to = models.ForeignKey(Class)

    def __str__(self):
        return self.user.username

    @property
    def fullname(self):
        return self.user.first_name + self.user.last_name

    class Meta:
        permissions = (("students_permission", "students_permission"),)
        ordering = ['-class_belong_to']


class Vote(models.Model):
    """
    保存某次问卷的信息
    """
    name = models.CharField(max_length=100)
    raised_by = models.ForeignKey(Teacher)
    class_invited = models.ManyToManyField(Class)
    start_date = models.DateField()
    end_date = models.DateField()
    save_name = models.BooleanField()

    def __str__(self):
        return self.name

    @property
    def is_out_of_date(self):
        """
        :return: 此Vote是否已经过期
        """
        return now().date() > self.end_time

    def is_student_voted(self, student):
        """
        :param student: 要检验的学生对象
        :return: 这个student是已经投票
        """
        return self.votepiece_set.filter(voted_by=student).exists()

    def invited_students(self):
        """
        :return: 被邀请的学生列表
        """
        return sum(map(lambda the_class: list(the_class.student_set.all()),
                       self.class_invited.all()), [])

    def voted_students(self):
        """
        :return: 已经投票的学生列表
        """
        return sum(map(lambda vote_piece: [vote_piece.voted_by],
                       VotePiece.objects.filter(belong_to_vote=self)), [])

    def voted_student_count(self):
        """
        :return: 已投票的学生数量
        """
        return self.votepiece_set.all().count()

    def invited_student_count(self):
        """
        :return: 被邀请的学生数量
        """
        return sum(map(lambda class_: class_.student_set.count(), self.class_invited.all()))


class Question(models.Model):
    """
    保存一个问题的信息
    """
    number = models.SmallIntegerField()
    belong_to_vote = models.ForeignKey(Vote)

    def __str__(self):
        return str(self.belong_to_vote) + ' ' + str(self.number) + '.'

    def voted_student_count(self):
        return self.votepiece_set.all().count()

    def voted_student_in_class_count(self, class_):
        return self.votepiece_set.filter(voted_by__class_belong_to=class_).count()

    def visible_classes(self):
        return self.belong_to_vote.class_invited.all()

    def visible_by_student(self, student):
        return student in self.belong_to_vote.invited_students()

    def voted_by_student(self, student):
        try:
            # todo:这个貌似可以化简
            return self in self.votepiece_set.get(voted_by=student).voted_questions.all()
        except ObjectDoesNotExist:
            return False


class VotePiece(models.Model):
    """
    保存一次Vote的信息
    """
    voted_by = models.ForeignKey(Student)
    belong_to_vote = models.ForeignKey(Vote)
    voted_questions = models.ManyToManyField(Question)

    def __str__(self):
        return str(self.voted_by) + ' 对 ' + str(self.belong_to_vote) + ' 的问题'


class Tag(models.Model):
    """
    知识点的Tag
    """
    name = models.CharField(max_length=64)
    attach_to_questions = models.ManyToManyField(Question)

    def __str__(self):
        return self.name

    def vote_people_count(self):
        ret = 0
        for question in self.attach_to_questions.all():
            ret += question.voted_student_count()
        return ret

    def visible_by_class(self, class_id):
        the_class = Class.objects.get(id=class_id)
        for question in self.attach_to_questions.all():
            if the_class in question.visible_classes():
                return True
        return False

    def voted_by_student(self, student):
        return any(map(lambda question: question.voted_by_student(student), self.attach_to_questions.all()))

    def voted_people_count_in_class(self, class_id):
        the_class = Class.objects.get(id=class_id)
        ret = 0
        for question in self.attach_to_questions.all():
            if the_class in question.visible_classes():
                ret += question.voted_student_in_class_count(the_class)
        return ret

    def student_vote_count(self, student):
        return sum((1 if question.voted_by_student(student) else 0 for question in self.attach_to_questions.all()))

e_homework/views/student_views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect

from ..models import *


@login_required
@permission_required('e_homework.students_permission')
def student(request):
    the_student = Student.objects.get(user=request.user)
    votes_invite_the_student = Vote.objects.filter(class_invited=the_student.class_belong_to)
    votes_voted_by_the_student = VotePiece.objects.filter(voted_by=the_student)
    return render(request, "student/student.html", {
        'unvote_count': votes_invite_the_student.count() - votes_voted_by_the_student.count(),
        'votes': votes_invite_the_student,
        'student': the_student
    })


@login_required
@permission_required('e_homework.students_permission')
def vote(request, vote_id):
    the_student = Student.objects.get(user=request.user)
    the_vote = Vote.objects.get(id=vote_id)
    if the_student not in the_vote.invited_students():
        return redirect('/student/')
    votes_invite_the_student = Vote.objects.filter(class_invited=the_student.class_belong_to)
    return render(request, "student/vote.html", {
        'vote': the_vote,
        'unvote_count': votes_invite_the_student.count() - VotePiece.objects.filter(
            voted_by=the_student).count(),
        'votes': votes_invite_the_student,
        'student': the_student
    })


@login_required
@permission_required('e_homework.students_permission')
def do_vote(request, vote_id):
    the_student = Student.objects.get(user=request.user)
    the_vote = Vote.objects.get(id=vote_id)
    if the_student not in the_vote.invited_students():
        return redirect('/student/')
    the_vote_piece = VotePiece.objects.get_or_create(voted_by=Student.objects.get(user=request.user),
                                                     belong_to_vote=Vote.objects.get(id=vote_id))[0]
    the_vote_piece.voted_questions.clear()
    for question_id in filter(lambda post_item: post_item != 'csrfmiddlewaretoken', request.POST):
        the_vote_piece.voted_questions.add(Question.objects.get(id=question_id))
    return redirect('/student/')


@login_required
@permission_required('e_homework.students_permission')
def tag_info(request):
    the_student = Student.objects.get(user=request.user)
    tags = map(lambda tag: {'name': tag.name, 'student_vote_count': tag.student_vote_count(the_student)},
               filter(lambda tag: tag.voted_by_student(the_student), Tag.objects.all()))
    return render(request, 'student/tag-info.html', {'tags': tags})

templates/student/student.html
{% extends "base.html" %}
{% block title %}e-homework 学生端{% endblock %}
{% block morestaticfiles %}
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static "css/student.css" %}">
{% endblock %}
{% block main %}
  <nav>
    <span class="open-nav-menu glyphicon glyphicon-tasks"></span>
    <a class="head-title">学生端</a>
    <ul>
      {#          todo:Maybe I can refactor it!#}
      <li class="normal-nav-item">
        <a id="homework-question-open">作业问题&nbsp;&nbsp;
          <span class="badge">{{ unvote_count }}</span>
          <span class="open-selection-bar open-selection-bar-desktop caret"></span>
          <span class="open-selection-bar open-selection-bar-mobile caret"></span>
        </a>
      </li>
      <li id="homework-question" class="expandable-nav-item">
        <ul>
          {% for vote in votes %}
            <li {% if student in vote.voted_students %}class="viewed"{% endif %}><a
                    href="{% url "vote" vote.id %}">{{ vote.name }}</a></li>
          {% endfor %}
        </ul>
      </li>
      <li class="normal-nav-item">
        <a id="homework-question-open">其他功能</a>
    </ul>
  </nav>
  <div class="content">
    {% block content %}
      <h2>欢迎访问e&#8209;homework学生端</h2>
      <a class="btn btn-danger" href="{% url "log-out" %}">退出</a>
    {% endblock %}
  </div>
  <script>
    $("nav").click(function () {
      $(this).addClass("open");
    });
    var $homework_question = $("#homework-question");
    $(".content").click(function () {
      $("nav").removeClass("open");
      $homework_question.removeClass("open");
      $(".open-selection-bar-mobile").css({"transform": "rotate(0.75turn)"});
    });
    $("#homework-question-open").click(function () {
      if ($homework_question.hasClass("open")) {
        $homework_question.removeClass("open");
        $(".open-selection-bar-desktop").css({"transform": "rotate(0turn)"});
        $(".open-selection-bar-mobile").css({"transform": "rotate(0.75turn)"});
      } else {
        $homework_question.addClass("open");
        $(".open-selection-bar-desktop").css({"transform": "rotate(0.5turn)"});
        $(".open-selection-bar-mobile").css({"transform": "rotate(0.25turn)"});
      }
    });
  </script>
{% endblock %}

templates/student/tag-info.html
{% extends 'student/student.html' %}
{% block content %}
  <div class="container-fluid">
    <div id="frequent-tags">
      <table class=" table table-hover" id="tag-list">
        <thead>
        <tr>
          <th>Tag</th>
          <th>提问次数</th>
        </tr>
        </thead>
        <tbody>
        {% for tag in tags %}
          <tr>
            <th>{{ tag.name }}</th>
            <th>{{ tag.student_vote_count }}</th>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% load staticfiles %}
{% endblock %}

templates/student/vote.html
{% extends "student/student.html" %}
{% block morestaticfiles %}
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static "css/student.css" %}">
  <link rel="stylesheet" href="{% static "css/checkbox-flat/blue.css" %}">
{% endblock %}
{% block content %}
  <h2>{{ vote.name }}</h2>
  <form method="post" action="{% url "do-vote" vote.id %}">{% csrf_token %}
    {% for question in vote.question_set.all|dictsort:'number' %}
      <div class="form-group checkbox">
        <input type="checkbox" class="form-control" id="{{ question.id }}" name="{{ question.id }}">
        <label for="{{ question.id }}">
          {{ question.number }}
        </label>
      </div>
    {% endfor %}
    <button class="btn btn-primary center-block" type="submit">确认</button>
  </form>
  <script src="{% static "js/icheck.min.js" %}"></script>
  <script>
    $(function () {
      $("input[type='checkbox']").iCheck({
        checkboxClass: 'icheckbox_flat-blue'
      });
    })
  </script>
{% endblock %}